backend:
  name: github
  branch: try/open-authoring
  repo: greatislander/selfdefined
  open_authoring: true
publish_mode: editorial_workflow
site_url: "https://nifty-snyder-07e6ef.netlify.com/"
media_folder: "11ty/images/uploads"
public_folder: "images/uploads"
collections:
  - name: "definitions"
    label: "Definitions"
    folder: "11ty/definitions"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "hidden"}
      - {label: "Defined", name: "defined", widget: "boolean"}
      # flag
        # - text
        # - level
      # speech
      # reading
        # - text, href
      # alt_words
      - {label: "Body", name: "body", widget: "markdown"}
